name: Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CSV_URL: "MLproject/data.csv"
  
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
          
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local
          
      # make new file .csv
      - name: Commit & push clean_data.csv
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add MLproject/clean_data.csv
          git diff --cached --quiet || git commit -m "chore: update clean_data.csv [skip ci]"
          git push
